# Ultralytics YOLO 🚀, AGPL-3.0 license
"""
Ultralytics modules.

Example:
    Visualize a module with Netron.
    ```python
    from ultralytics.nn.modules import *
    import torch
    import os

    x = torch.ones(1, 128, 40, 40)
    m = Conv(128, 128)
    f = f'{m._get_name()}.onnx'
    torch.onnx.export(m, x, f)
    os.system(f'onnxsim {f} {f} && open {f}')
    ```
"""

from .block import (
    C1,
    C2,
    C3,
    C3TR,
    DFL,
    SPP,
    SPPELAN,
    SPPF,
    ADown,
    BNContrastiveHead,
    Bottleneck,
    BottleneckCSP,
    C2f,
    C2fAttn,
    C3Ghost,
    C3x,
    CBFuse,
    CBLinear,
    ContrastiveHead,
    GhostBottleneck,
    HGBlock,
    HGStem,
    ImagePoolingAttn,
    Proto,
    RepC3,
    RepNCSPELAN4,
    ResNetLayer,
    Silence,
    Faster_C2f,
    C2f_MLCA,
    MBConv,
    C2f_EMBC,
    C2f_DAttention,
    SDFM,
    C2f_Star_CAA,
    C2f_DynamicConv,
    RFCBAMConv,C2f_RFCBAMConv,RFAConv,C2f_RFAConv,
    C2f_DRB,
    PSFM,
    C2f_Star,
    FocusFeature,
    ContextFusionConcat,
    PCE,
    CSGDF ,
    DySample,
    C2f_DSCA

)
from .conv import (
    CBAM,
    ChannelAttention,
    Concat,
    Conv,
    Conv2,
    ConvTranspose,
    DWConv,
    DWConvTranspose2d,
    Focus,
    GhostConv,
    LightConv,
    RepConv,
    SpatialAttention,
)
from .head import OBB, Classify, Detect, Pose, RTDETRDecoder, Segment, WorldDetect, Detect_SEAM, Detect_MultiSEAM,v10Detect,Detect_NMSFree,DTHead,AYHead
from .transformer import (
    AIFI,
    MLP,
    DeformableTransformerDecoder,
    DeformableTransformerDecoderLayer,
    LayerNorm2d,
    MLPBlock,
    MSDeformAttn,
    TransformerBlock,
    TransformerEncoderLayer,
    TransformerLayer,
)
# from .faster_c2f import Faster_Block,Faster_C2f
from .BRA import BiLevelRoutingAttention
__all__ = (
    "Conv",
    "Conv2",
    "LightConv",
    "RepConv",
    "DWConv",
    "DWConvTranspose2d",
    "ConvTranspose",
    "Focus",
    "GhostConv",
    "ChannelAttention",
    "SpatialAttention",
    "CBAM",
    "Concat",
    "TransformerLayer",
    "TransformerBlock",
    "MLPBlock",
    "LayerNorm2d",
    "DFL",
    "HGBlock",
    "HGStem",
    "SPP",
    "SPPF",
    "C1",
    "C2",
    "C3",
    "C2f",
    "C2fAttn",
    "C3x",
    "C3TR",
    "C3Ghost",
    "GhostBottleneck",
    "Bottleneck",
    "BottleneckCSP",
    "Proto",
    "Detect",
    "Segment",
    "Pose",
    "Classify",
    "TransformerEncoderLayer",
    "RepC3",
    "RTDETRDecoder",
    "AIFI",
    "DeformableTransformerDecoder",
    "DeformableTransformerDecoderLayer",
    "MSDeformAttn",
    "MLP",
    "ResNetLayer",
    "OBB",
    "WorldDetect",
    "ImagePoolingAttn",
    "ContrastiveHead",
    "BNContrastiveHead",
    "RepNCSPELAN4",
    "ADown",
    "SPPELAN",
    "CBFuse",
    "CBLinear",
    "Silence",
    "Faster_C2f",
    "C2f_MLCA",
    "Faster_Block",
    "BiLevelRoutingAttention",
    "MBConv",
    "C2f_EMBC",
    "C2f_DAttention",
    "SDFM",
    "C2f_Star_CAA",
    "C2f_DynamicConv",
    "RFCBAMConv","C2f_RFCBAMConv","RFAConv","C2f_RFAConv",
    "C2f_DRB",
    "PSFM",
    "C2f_Star",
    "Detect_SEAM", "Detect_MultiSEAM",
    "FocusFeature",
    "ContextFusionConcat",
    "v10Detect",
    "Detect_NMSFree",
    "DTHead",
    "PCE",
    "CSGDF ",
    "DySample",
    "AYHead",
    "C2f_DSCA"
)
